pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./allocate.html","DelesinPPS Features &#62; Allocate","Allocate",""],
["./allocate_1.html","DelesinPPS User Guide &#62; Allocate","Allocate",""],
["./allocate_2.html","Using DelesinPPS &#62; Allocate","Allocate",""],
["./alternative_use_cases.html","Overview of DelesinPPS &#62; Alternative Use Cases","Alternative Use Cases",""],
["./change_in_interest_rate_behavior.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Structural Influences on Returns &#62; Change in Interest Rate Behavior","Change in Interest Rate Behavior",""],
["./considerations_for_portfolio_construction.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction","Considerations for Portfolio Construction",""],
["./delesin_pps_stages.html","Overview of DelesinPPS &#62; Delesin PPS Stages","Delesin PPS Stages",""],
["./direct_entry_of_securities.html","Using DelesinPPS &#62; Select &#62; Direct Entry of Securities","Direct Entry of Securities",""],
["./down-side_variance.html","Portfolio Analysis: An Abridged History &#62; Portfolio Optimization Methods &#62; Down-Side Variance","Down-Side Variance",""],
["./editing_solutions.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Editing Solutions","Editing Solutions",""],
["./end_of_bretton-woods.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Structural Influences on Returns &#62; End of Bretton-Woods","End of Bretton-Woods",""],
["./export_selected_solution.html","Using DelesinPPS &#62; Utilize &#62; Export Selected Solution","Export Selected Solution",""],
["./financial_fundamentals.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Financial Fundamentals","Financial Fundamentals",""],
["./forecast.html","DelesinPPS Features &#62; Forecast","Forecast",""],
["./forecast_1.html","DelesinPPS User Guide &#62; Forecast","Forecast",""],
["./frame.html","DelesinPPS Features &#62; Frame","Frame",""],
["./frame_1.html","DelesinPPS User Guide &#62; Frame","Frame",""],
["./frame_2.html","Using DelesinPPS &#62; Frame","Frame",""],
["./globalization_of_markets.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Structural Influences on Returns &#62; Globalization of Markets","Globalization of Markets",""],
["./government_tax_and_subsidy_intervention_and_centra.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Structural Influences on Returns &#62; Government Tax and Subsidy Intervention and Central Bank Policy","Government Tax and Subsidy Intervention and Central Bank Policy",""],
["./hlk497330853.html","Using DelesinPPS &#62; Frame &#62; Using the Reference Period Pop-up","Using the Reference Period Pop-up",""],
["./hlk497331494.html","Using DelesinPPS &#62; Frame &#62; Using the Reference Period Pop-up &#62; Calendar Reference Period Specification","Calendar Reference Period Specification",""],
["./hlk497331606.html","Using DelesinPPS &#62; Frame &#62; Using the Reference Period Pop-up &#62; Graph Slider Reference Period Specification","Graph Slider Reference Period Specification",""],
["./hlk497332122.html","Using DelesinPPS &#62; Frame &#62; Using the Reference Period Pop-up &#62; Completion of Reference Period Specification","Completion of Reference Period Specification",""],
["./hlk497332969.html","Using DelesinPPS &#62; Select","Select",""],
["./hlk497334270.html","Using DelesinPPS &#62; Select &#62; Security Sector, Exchange and Cap Size Filtering","Security Sector, Exchange and Cap Size Filtering",""],
["./hlk497334323.html","Using DelesinPPS &#62; Select &#62; Security Sector, Exchange and Cap Size Filtering &#62; Security Sector, Exchange and Cap Size Filtering Example","Security Sector, Exchange and Cap Size Filtering Example",""],
["./hlk497334598.html","Using DelesinPPS &#62; Select &#62; Securities Selection Wizard Overview","Securities Selection Wizard Overview",""],
["./hlk497383009.html","Using DelesinPPS &#62; Select &#62; Deleting Selected Securities","Deleting Selected Securities",""],
["./hlk497384081.html","Using DelesinPPS &#62; Select &#62; Adding to the Selected Securities List","Adding to the Selected Securities List",""],
["./hlk497384118.html","Using DelesinPPS &#62; Forecast","Forecast",""],
["./hlk497384166.html","Using DelesinPPS &#62; Forecast &#62; Specify The Holding Period","Specify The Holding Period",""],
["./hlk497384301.html","Using DelesinPPS &#62; Forecast &#62; Specify Parameters for Technical Charts","Specify Parameters for Technical Charts",""],
["./hlk497384686.html","Using DelesinPPS &#62; Forecast &#62; Forecast Assistance Wizard Overview","Forecast Assistance Wizard Overview",""],
["./hlk497390168.html","Using DelesinPPS &#62; Forecast &#62; Choosing the Forecast Wizard Parameters","Choosing the Forecast Wizard Parameters",""],
["./hlk497390758.html","Using DelesinPPS &#62; Forecast &#62; Modifying Select Securities Forecasts − Using the Distributions","Modifying Select Securities Forecasts − Using the Distributions",""],
["./hlk497396160.html","Using DelesinPPS &#62; Forecast &#62; Returning to the Main Screen.","Returning to the Main Screen.",""],
["./hlk497401157.html","Using DelesinPPS &#62; Allocate &#62; Setting Portfolio Allocation Parameters","Setting Portfolio Allocation Parameters",""],
["./hlk497417163.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; A Specific Solution","A Specific Solution",""],
["./hlk497427544.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Using the Frontier Wizard","Using the Frontier Wizard",""],
["./hlk497427677.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Using the Frontier Wizard &#62; Exploring Alternative Frontier Solutions","Exploring Alternative Frontier Solutions",""],
["./hlk497428745.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Resulting Portfolio Values","Resulting Portfolio Values",""],
["./hlk497429085.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Allocation Summary","Allocation Summary",""],
["./hlk497429377.html","Using DelesinPPS &#62; Utilize","Utilize",""],
["./hlk497432375.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade","Submit for Trade",""],
["./hlk497432396.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; The DelesinPPS Trade Calculator &#62; Selecting the Securities to Trade","Selecting the Securities to Trade",""],
["./hlk497432437.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; The DelesinPPS Trade Calculator &#62; Allowing Allocation Limit to be Exceeded","Allowing Allocation Limit to be Exceeded",""],
["./hlk497432787.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; TradeStation Order, Position and Balance Reports","TradeStation Order, Position and Balance Reports",""],
["./hlk497432964.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; A Few Minutes After Submission","A Few Minutes After Submission",""],
["./hlk498944625.html","Portfolio Analysis: An Abridged History","Portfolio Analysis: An Abridged History",""],
["./hlk498945104.html","DelesinPPS Features","DelesinPPS Features",""],
["./hlk498945128.html","DelesinPPS User Guide","DelesinPPS User Guide",""],
["./hlk498947945.html","Overview of DelesinPPS","Overview of DelesinPPS",""],
["./hlk498948090.html","Entering DelesinPPS","Entering DelesinPPS",""],
["./hlk499017777.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Using the Frontier Wizard &#62; Set the Holding Period","Set the Holding Period",""],
["./hlk499018099.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Using the Frontier Wizard &#62; Initial Screen and Progress Bar","Initial Screen and Progress Bar",""],
["./hlk499019394.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization &#62; Using the Frontier Wizard &#62; Frontier Wizard Results","Frontier Wizard Results",""],
["./hlk499026617.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; The DelesinPPS Trade Calculator &#62; Submitting Orders For Trade Execution","Submitting Orders For Trade Execution",""],
["./inhomogeneity_of_market_liquidity_among_securities.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Inhomogeneity of Market Liquidity Among Securities","Inhomogeneity of Market Liquidity Among Securities",""],
["./investor_diversification_preferences_andor_fiduci.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Investor Diversification Preferences and/or Fiduciary Guidelines","Investor Diversification Preferences and/or Fiduciary Guidelines",""],
["./logging_in.html","Entering DelesinPPS &#62; Logging In","Logging In",""],
["./market_volatility.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Market Volatility","Market Volatility",""],
["./mean-variance.html","Portfolio Analysis: An Abridged History &#62; Portfolio Optimization Methods &#62; Mean-Variance","Mean-Variance",""],
["./modifying_select_securities_forecasts_-_setting_ex.html","Using DelesinPPS &#62; Forecast &#62; Modifying Select Securities Forecasts − Setting Expected Price","Modifying Select Securities Forecasts − Setting Expected Price",""],
["./performing_the_optimization.html","Using DelesinPPS &#62; Allocate &#62; Performing the Optimization","Performing the Optimization",""],
["./portfolio_optimization_methods.html","Portfolio Analysis: An Abridged History &#62; Portfolio Optimization Methods","Portfolio Optimization Methods",""],
["./portfolio_rebalancing_some_comments.html","Portfolio Rebalancing: Some Comments","Portfolio Rebalancing: Some Comments",""],
["./save_selected_solution.html","Using DelesinPPS &#62; Utilize &#62; Save Selected Solution","Save Selected Solution",""],
["./sectors_exchanges_and_capital_size.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Sectors, Exchanges and Capital Size","Sectors, Exchanges and Capital Size",""],
["./security_returns_and_their_variabilities_in_relati.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Security Returns and Their Variabilities In Relation to Each Other and In Relation to the Market","Security Returns and Their Variabilities In Relation to Each Other and In Relation to the Market",""],
["./select.html","DelesinPPS Features &#62; Select","Select",""],
["./select_1.html","DelesinPPS User Guide &#62; Select","Select",""],
["./setting_portfolio_parameters.html","Using DelesinPPS &#62; Frame &#62; Setting Portfolio Parameters","Setting Portfolio Parameters",""],
["./setting_the_reference_period.html","Using DelesinPPS &#62; Frame &#62; Setting the Reference Period","Setting the Reference Period",""],
["./setting_upper_bounds_on_allocations.html","Using DelesinPPS &#62; Allocate &#62; Setting Upper Bounds on Allocations","Setting Upper Bounds on Allocations",""],
["./structural_influences_on_returns.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Structural Influences on Returns","Structural Influences on Returns",""],
["./technical_indicators.html","Portfolio Analysis: An Abridged History &#62; Considerations for Portfolio Construction &#62; Technical Indicators","Technical Indicators",""],
["./the_delesinpps_trade_calculator.html","Using DelesinPPS &#62; Utilize &#62; Submit for Trade &#62; The DelesinPPS Trade Calculator","The DelesinPPS Trade Calculator",""],
["./the_help_selection_menu.html","Entering DelesinPPS &#62; The Help Selection Menu","The Help Selection Menu",""],
["./the_initial_screen.html","Entering DelesinPPS &#62; The Initial Screen","The Initial Screen",""],
["./the_login_dialogue.html","Entering DelesinPPS &#62; The Login Dialogue","The Login Dialogue",""],
["./using_delesinpps.html","Using DelesinPPS","Using DelesinPPS",""],
["./using_selection_wizard_corral_to_find_the_best_30_.html","Using DelesinPPS &#62; Select &#62; Securities Selection Wizard Overview &#62; Using Selection Wizard Corral to find the Best 30 of the Remaining Securities","Using Selection Wizard Corral to find the Best 30 of the Remaining Securities",""],
["./using_the_selection_wizard_filters_example_1.html","Using DelesinPPS &#62; Select &#62; Securities Selection Wizard Overview &#62; Using the Selection Wizard Filters Example 1","Using the Selection Wizard Filters Example 1",""],
["./using_the_selection_wizard_filters_example_2.html","Using DelesinPPS &#62; Select &#62; Securities Selection Wizard Overview &#62; Using the Selection Wizard Filters Example 2","Using the Selection Wizard Filters Example 2",""],
["./utilize.html","DelesinPPS Features &#62; Utilize","Utilize",""],
["./utilize_1.html","DelesinPPS User Guide &#62; Utilize","Utilize",""],
["./value_at_risk.html","Portfolio Analysis: An Abridged History &#62; Portfolio Optimization Methods &#62; Value at Risk","Value at Risk",""]];
